### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by Asteliks** [JOSM/indoorhelper#10]
Just wanted to say that you are doing a great job and I can not wait for the next releases with the  [planed](https://github.com/JOSM/indoorhelper/projects/3) improvements. Especially the one with "Workflow of start mapping objects on a new level should be improved.". To be honest actually I'm waiting for this feature and don't want to get back to indor mapping before it arrives.

**Comment by rebeccasc** [comment]
@Asteliks thanks, it's nice to get some feedback!
Not much happened here in the last few weeks but this will change soon!

> "Workflow of start mapping objects on a new level should be improved."

Do you have any ideas how a useful functionality could look like? At the moment I'm still thinking about a good implementation... so feel free to share your ideas :)

**Comment by Asteliks** [comment]
Actually, I do though these might be a bit hard to explain here in the issues, but I will try. First of all, my experience with the plugin is limited to the implementation of the indoor map of [CW PP](https://openlevelup.net/?l=0#20/52.40417/16.94951) (building being part of the Poznan university of technology). My question here is what is your experience with using this plugin for indoor mapping? Perhaps I could provide you with the data based on which I was able to create the mentioned above map and based on that some ideas may come to mind. 
As you can probably see some time has passed and thus, I do not remember all the details I had in mind at that time but the one thing that I remember is the trouble with the displayed level management. I wish one could completely turn off certain levels form displaying and select the transparency and perhaps color for certain other levels because in higher buildings things tend to get messy. For example, my building has a cellar, ground and the first floor. In the current state when mapping the first floor I see the ground and cellar though a bit faded still there whereas I would like to see the ground floor at most.

**Comment by rebeccasc** [comment]
I've had a look into the [OpenLevelUp](https://openlevelup.net/?l=0#17/52.40418/16.95034) tool but could not reach the edit-mode to reproduce the problem. Can you please provide a detailed way of how you edit the data? Do you use the online OpenLevelUp tool or the installed [JOSM](https://josm.openstreetmap.de/)?

**Comment by Asteliks** [comment]
> I've had a look into the [OpenLevelUp](https://openlevelup.net/?l=0#17/52.40418/16.95034) tool but could not reach the edit-mode to reproduce the problem. Can you please provide a detailed way of how you edit the data? Do you use the online OpenLevelUp tool or the installed [JOSM](https://josm.openstreetmap.de/)?

I've used JOSM with your plugin to input the data and OpenLevelUp to display it

**Comment by rebeccasc** [comment]
If I get you right you want to handle the visibilty of level data.
There are two ways to do this:
1. Make use of the JOSM [Autofilter](https://josm.openstreetmap.de/wiki/Help/Dialog/Filter#Autofilters). You can enable or disable the different levels using the buttons. This function only allows you to enable or disable the data not to hide it (I guess this is your problem right now). You can still use it if you apply the Map Paint Style "Indoor" which comes with the indoor helper plugin. The mapstyle colors indoor objects with a specific color (if you use the [SIT schema](https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging) for tagging objects). Here is an [example ](https://wiki.openstreetmap.org/w/images/5/52/Screenshot_editor.png) of how it looks. You can enable the Map Paint Style dialog at `Windows -> Map Paint Styles`. If you cannot find the "Indoor" style in list, you might have to enable it using `Edit -> Preferences... -> Map Settings -> Map Paint Styles`
2. Set your own filter. You can set your own filter to hide floors. For example if your first level objects are tagged with `level=1` you can apply the filter `level=1` to address all the objects. Having a look at the filter list (in Filter dialog) you can find two checkboxes next to the filter name (E,H). One for enabling/disabling data and the other to hide the data. If you set your own filter make sure you don't use the JOSM [Autofilter](https://josm.openstreetmap.de/wiki/Help/Dialog/Filter#Autofilters). The autofilter will override your own filter. The Filters dialog can be enabled at `Windows -> Filters`. For more information about how to set filters have a look at the [wiki](https://josm.openstreetmap.de/wiki/Help/Dialog/Filter)

**Comment by rebeccasc** [comment]
Added a [project cars](https://github.com/JOSM/indoorhelper/projects/3#card-58644509) regarding this
