### ISSUE TITLE
indoorhelper freezes JOSM

### ISSUE THREAD

**Issue by GerdP** [JOSM/indoorhelper#7]
See https://josm.openstreetmap.de/ticket/19618
I wonder if the code to handle tag repeat_on did ever work? I tried with older versions downto r14153 of JOSM and they all freeze.

**Comment by rebeccasc** [comment]
Fixed in https://github.com/JOSM/indoorhelper/commit/e3ea14b72a8b857982554b038c0e622de3d7b4f4. Will be part of the next release.

**Comment by GerdP** [comment]
Thanks for looking into this.
I wonder why you use this iteration
for (Map.Entry<String, String> entry : primitive.getInterestingTags().entrySet()) {
  if (entry.getKey().equals(key)) {
foo();
  }
}
..
you can use 
primitive.get(key) 
to retrive the value of a tag.

I also wonder why the loop calls
primitive.setDisabledType(true);
for a primitive that already is disabled.

**Comment by rebeccasc** [comment]
I removed the unnecessary code lines and refactored a little in https://github.com/JOSM/indoorhelper/commit/cbdbae9e9ef583e9bd635e0ba8e034fb62c4c425. Thanks for the review!

**Comment by rebeccasc** [comment]
See [Release v.1.1](https://github.com/JOSM/indoorhelper/releases/tag/v.1.1).
